### ISSUE TITLE
rebuild with 0.11.x not working

### ISSUE THREAD

**Issue by kamesh-a** [mscdex/spellcheck#5]
Hello,
I am trying to rebuild spellcheck with 
node-gyp rebuild --target=0.11.13 but it is getting compiled but compiles fine in 0.10.x. module version is 
11 in 10x and in 0.11.x module are 13. there is class happening.

Mac OS X 10.9.4

Attaching stack trace.

node-gyp rebuild --target=0.11.13
Password:
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.1
gyp info using node@0.10.30 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kamesh/node_modules/spellcheck/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kamesh/.node-gyp/0.11.13/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/kamesh/.node-gyp/0.11.13',
gyp info spawn args   '-Dmodule_root_dir=/Users/kamesh/node_modules/spellcheck',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/affentry.o
../deps/hunspell/src/hunspell/affentry.cxx:544:47: warning: while loop has empty
      body [-Wempty-body]
                        while (p && *p != ']' && (p = nextchar(p)));
                                                                   ^
../deps/hunspell/src/hunspell/affentry.cxx:544:47: note: put the semicolon on a
      separate line to silence this warning
1 warning generated.
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/affixmgr.o
In file included from ../deps/hunspell/src/hunspell/affixmgr.cxx:12:
../deps/hunspell/src/hunspell/affentry.hxx:30:105: warning: implicit conversion
      of NULL constant to 'unsigned short' [-Wnull-conversion]
  ...char * word, int len, char in_compound, const FLAG needflag = NULL);
                                                                 ~ ^~~~
                                                                   0
../deps/hunspell/src/hunspell/affentry.hxx:93:114: warning: implicit conversion
      of NULL constant to 'unsigned short' [-Wnull-conversion]
  ...int len, int optflags, PfxEntry* ppfx, const FLAG needflag = NULL);
                                                                ~ ^~~~
                                                                  0
../deps/hunspell/src/hunspell/affixmgr.cxx:3654:65: warning: 'strncmp' call
      operates on objects of type 'const char' while the size is based on a
      different type 'const char *' [-Wsizeof-pointer-memaccess]
  ...if (strncmp(piece, keyword, sizeof(keyword)) != 0) {
                        ~~~~~~~         ^~~~~~~
../deps/hunspell/src/hunspell/affixmgr.cxx:3654:65: note: did you mean to
      provide an explicit length?
  ...if (strncmp(piece, keyword, sizeof(keyword)) != 0) {
                                        ^~~~~~~
3 warnings generated.
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/csutil.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/dictmgr.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/filemgr.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/hashmgr.o
In file included from ../deps/hunspell/src/hunspell/hashmgr.cxx:9:
../deps/hunspell/src/hunspell/hashmgr.hxx:17:21: warning: private field
      'userword' is not used [-Wunused-private-field]
  int               userword;
                    ^
1 warning generated.
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/hunspell.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/hunzip.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/phonet.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/replist.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/suggestmgr.o
  LIBTOOL-STATIC Release/hunspell.a
  CXX(target) Release/obj.target/spellcheck/src/spellcheck.o
../src/spellcheck.cc:11:5: error: unknown type name 'uv_work_t'
    uv_work_t request;
    ^
../src/spellcheck.cc:26:27: error: expected class name
class SpellCheck : public ObjectWrap {
                          ^
../src/spellcheck.cc:39:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> New(const Arguments& args) {
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/kamesh/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/spellcheck.cc:75:38: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Check(const Arguments& args) {
                                     ^~~~~~~~~
                                     v8::internal::Arguments
/Users/kamesh/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/spellcheck.cc:109:27: error: unknown type name 'uv_work_t'
    static void CheckWork(uv_work_t* req) {
                          ^
../src/spellcheck.cc:122:28: error: unknown type name 'uv_work_t'
    static void CheckAfter(uv_work_t* req) {
                           ^
../src/spellcheck.cc:40:19: error: calling a protected constructor of class 'v8::HandleScope'
      HandleScope scope;
                  ^
/Users/kamesh/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/spellcheck.cc:44:16: error: member access into incomplete type 'const v8::internal::Arguments'
      if (!args.IsConstructCall()) {
               ^
/Users/kamesh/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/spellcheck.cc:46:11: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
          String::New("Use `new` to create instances of this object.")
          ^~~~~~~~~~~
          New
../src/spellcheck.cc:39:26: note: 'New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/spellcheck.cc:46:23: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of type
      'const char [46]'
          String::New("Use `new` to create instances of this object.")
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/spellcheck.cc:39:47: note: passing argument to parameter 'args' here
    static Handle<Value> New(const Arguments& args) {
                                              ^
../src/spellcheck.cc:50:15: error: member access into incomplete type 'const v8::internal::Arguments'
      if (args.Length() != 2) {
              ^
/Users/kamesh/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/spellcheck.cc:52:11: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
          String::New("Expecting two arguments")
          ^~~~~~~~~~~
          New
../src/spellcheck.cc:39:26: note: 'New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/spellcheck.cc:52:23: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of type
      'const char [24]'
          String::New("Expecting two arguments")
                      ^~~~~~~~~~~~~~~~~~~~~~~~~
../src/spellcheck.cc:39:47: note: passing argument to parameter 'args' here
    static Handle<Value> New(const Arguments& args) {
                                              ^
../src/spellcheck.cc:54:23: error: type 'const v8::internal::Arguments' does not provide a subscript operator
      } else if (!args[0]->IsString()) {
                  ~~~~^~
../src/spellcheck.cc:56:11: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
          String::New("First argument must be a string")
          ^~~~~~~~~~~
          New
../src/spellcheck.cc:39:26: note: 'New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/spellcheck.cc:56:23: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of type
      'const char [32]'
          String::New("First argument must be a string")
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/spellcheck.cc:39:47: note: passing argument to parameter 'args' here
    static Handle<Value> New(const Arguments& args) {
                                              ^
../src/spellcheck.cc:58:23: error: type 'const v8::internal::Arguments' does not provide a subscript operator
      } else if (!args[1]->IsString()) {
                  ~~~~^~
../src/spellcheck.cc:60:11: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
          String::New("Second argument must be a string")
          ^~~~~~~~~~~
          New
../src/spellcheck.cc:39:26: note: 'New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/spellcheck.cc:60:23: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of type
      'const char [33]'
          String::New("Second argument must be a string")
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/spellcheck.cc:39:47: note: passing argument to parameter 'args' here
    static Handle<Value> New(const Arguments& args) {
                                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/spellcheck/src/spellcheck.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild" "--target=0.11.13"
gyp ERR! cwd /Users/kamesh/node_modules/spellcheck
gyp ERR! node -v v0.10.30
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

**Comment by blainesch** [comment]
Similar problems

~~~
-> % npm install --save spellcheck
npm WARN package.json baser@1.0.0 No description
npm WARN package.json baser@1.0.0 No repository field.
npm WARN package.json baser@1.0.0 No README data
\
> spellcheck@0.0.4 install /Users/bschmeisser/sites/devup/apps/baser/node_modules/spellcheck
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/affentry.o
../deps/hunspell/src/hunspell/affentry.cxx:544:47: warning: while loop has empty body [-Wempty-body]
                        while (p && *p != ']' && (p = nextchar(p)));
                                                                   ^
../deps/hunspell/src/hunspell/affentry.cxx:544:47: note: put the semicolon on a separate line to silence this warning
1 warning generated.
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/affixmgr.o
In file included from ../deps/hunspell/src/hunspell/affixmgr.cxx:12:
../deps/hunspell/src/hunspell/affentry.hxx:30:105: warning: implicit conversion of NULL constant to 'unsigned short' [-Wnull-conversion]
  struct hentry *      check_twosfx(const char * word, int len, char in_compound, const FLAG needflag = NULL);
                                                                                                      ~ ^~~~
                                                                                                        0
../deps/hunspell/src/hunspell/affentry.hxx:93:114: warning: implicit conversion of NULL constant to 'unsigned short' [-Wnull-conversion]
  struct hentry *   check_twosfx(const char * word, int len, int optflags, PfxEntry* ppfx, const FLAG needflag = NULL);
                                                                                                               ~ ^~~~
                                                                                                                 0
../deps/hunspell/src/hunspell/affixmgr.cxx:3654:65: warning: 'strncmp' call operates on objects of type 'const char' while the size is based on a different type 'const char *' [-Wsizeof-pointer-memaccess]
                             if (strncmp(piece, keyword, sizeof(keyword)) != 0) {
                                                ~~~~~~~         ^~~~~~~
../deps/hunspell/src/hunspell/affixmgr.cxx:3654:65: note: did you mean to provide an explicit length?
                             if (strncmp(piece, keyword, sizeof(keyword)) != 0) {
                                                                ^~~~~~~
3 warnings generated.
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/csutil.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/dictmgr.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/filemgr.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/hashmgr.o
In file included from ../deps/hunspell/src/hunspell/hashmgr.cxx:9:
../deps/hunspell/src/hunspell/hashmgr.hxx:17:21: warning: private field 'userword' is not used [-Wunused-private-field]
  int               userword;
                    ^
1 warning generated.
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/hunspell.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/hunzip.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/phonet.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/replist.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/suggestmgr.o
  LIBTOOL-STATIC Release/hunspell.a
  CXX(target) Release/obj.target/spellcheck/src/spellcheck.o
../src/spellcheck.cc:11:5: error: unknown type name 'uv_work_t'
    uv_work_t request;
    ^
../src/spellcheck.cc:26:27: error: expected class name
class SpellCheck : public ObjectWrap {
                          ^
../src/spellcheck.cc:39:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> New(const Arguments& args) {
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/bschmeisser/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/spellcheck.cc:75:38: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Check(const Arguments& args) {
                                     ^~~~~~~~~
                                     v8::internal::Arguments
/Users/bschmeisser/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/spellcheck.cc:109:27: error: unknown type name 'uv_work_t'
    static void CheckWork(uv_work_t* req) {
                          ^
../src/spellcheck.cc:122:28: error: unknown type name 'uv_work_t'
    static void CheckAfter(uv_work_t* req) {
                           ^
../src/spellcheck.cc:40:19: error: calling a protected constructor of class 'v8::HandleScope'
      HandleScope scope;
                  ^
/Users/bschmeisser/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/spellcheck.cc:44:16: error: member access into incomplete type 'const v8::internal::Arguments'
      if (!args.IsConstructCall()) {
               ^
/Users/bschmeisser/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/spellcheck.cc:46:11: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
          String::New("Use `new` to create instances of this object.")
          ^~~~~~~~~~~
          New
../src/spellcheck.cc:39:26: note: 'New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/spellcheck.cc:46:23: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of type 'const char [46]'
          String::New("Use `new` to create instances of this object.")
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/spellcheck.cc:39:47: note: passing argument to parameter 'args' here
    static Handle<Value> New(const Arguments& args) {
                                              ^
../src/spellcheck.cc:50:15: error: member access into incomplete type 'const v8::internal::Arguments'
      if (args.Length() != 2) {
              ^
/Users/bschmeisser/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/spellcheck.cc:52:11: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
          String::New("Expecting two arguments")
          ^~~~~~~~~~~
          New
../src/spellcheck.cc:39:26: note: 'New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/spellcheck.cc:52:23: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of type 'const char [24]'
          String::New("Expecting two arguments")
                      ^~~~~~~~~~~~~~~~~~~~~~~~~
../src/spellcheck.cc:39:47: note: passing argument to parameter 'args' here
    static Handle<Value> New(const Arguments& args) {
                                              ^
../src/spellcheck.cc:54:23: error: type 'const v8::internal::Arguments' does not provide a subscript operator
      } else if (!args[0]->IsString()) {
                  ~~~~^~
../src/spellcheck.cc:56:11: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
          String::New("First argument must be a string")
          ^~~~~~~~~~~
          New
../src/spellcheck.cc:39:26: note: 'New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/spellcheck.cc:56:23: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of type 'const char [32]'
          String::New("First argument must be a string")
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/spellcheck.cc:39:47: note: passing argument to parameter 'args' here
    static Handle<Value> New(const Arguments& args) {
                                              ^
../src/spellcheck.cc:58:23: error: type 'const v8::internal::Arguments' does not provide a subscript operator
      } else if (!args[1]->IsString()) {
                  ~~~~^~
../src/spellcheck.cc:60:11: error: no member named 'New' in 'v8::String'; did you mean simply 'New'?
          String::New("Second argument must be a string")
          ^~~~~~~~~~~
          New
../src/spellcheck.cc:39:26: note: 'New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/spellcheck.cc:60:23: error: reference to type 'const v8::internal::Arguments' could not bind to an lvalue of type 'const char [33]'
          String::New("Second argument must be a string")
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/spellcheck.cc:39:47: note: passing argument to parameter 'args' here
    static Handle<Value> New(const Arguments& args) {
                                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/spellcheck/src/spellcheck.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bschmeisser/sites/devup/apps/baser/node_modules/spellcheck
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "spellcheck"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! spellcheck@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spellcheck@0.0.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the spellcheck package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls spellcheck
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bschmeisser/sites/devup/apps/baser/npm-debug.log
~~~

~~~
-> % node-gyp --version
v1.0.3
-> % node --version
v0.12.0
-> % npm --version
2.5.1
~~~

**Comment by mscdex** [comment]
Yeah I haven't had time to nan-ize this addon yet and I'm not sure when I will get to it. If someone wants to submit a PR to nan-ize it in the meantime, PRs are welcome.

**Comment by mscdex** [comment]
This is now fixed as of 03f161880e / v0.0.5.

**Comment by kamesh-a** [comment]
Hello ,
Thanks for working on this.

```
node --version = v0.11.9
npm --version = 1.3.15
node-gyp --version = v1.0.3
```

But still not able to re-build it succssfully

Attaching the stack trace : 

```
node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.3
gyp info using node@0.11.9 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/HD_II/spell/spellcheck/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/kamesharumugam/.node-gyp/0.11.9/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/kamesharumugam/.node-gyp/0.11.9',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/HD_II/spell/spellcheck',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/affentry.o
../deps/hunspell/src/hunspell/affentry.cxx:544:47: warning: while loop has empty body [-Wempty-body]
                        while (p && *p != ']' && (p = nextchar(p)));
                                                                   ^
../deps/hunspell/src/hunspell/affentry.cxx:544:47: note: put the semicolon on a separate line to silence this warning
1 warning generated.
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/affixmgr.o
In file included from ../deps/hunspell/src/hunspell/affixmgr.cxx:12:
../deps/hunspell/src/hunspell/affentry.hxx:30:105: warning: implicit conversion of NULL constant to 'unsigned short'
      [-Wnull-conversion]
  struct hentry *      check_twosfx(const char * word, int len, char in_compound, const FLAG needflag = NULL);
                                                                                                      ~ ^~~~
                                                                                                        0
../deps/hunspell/src/hunspell/affentry.hxx:93:114: warning: implicit conversion of NULL constant to 'unsigned short'
      [-Wnull-conversion]
  struct hentry *   check_twosfx(const char * word, int len, int optflags, PfxEntry* ppfx, const FLAG needflag = NULL);
                                                                                                               ~ ^~~~
                                                                                                                 0
../deps/hunspell/src/hunspell/affixmgr.cxx:3654:65: warning: 'strncmp' call operates on objects of type 'const char' while the
      size is based on a different type 'const char *' [-Wsizeof-pointer-memaccess]
                             if (strncmp(piece, keyword, sizeof(keyword)) != 0) {
                                                ~~~~~~~         ^~~~~~~
../deps/hunspell/src/hunspell/affixmgr.cxx:3654:65: note: did you mean to provide an explicit length?
                             if (strncmp(piece, keyword, sizeof(keyword)) != 0) {
                                                                ^~~~~~~
3 warnings generated.
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/csutil.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/dictmgr.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/filemgr.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/hashmgr.o
In file included from ../deps/hunspell/src/hunspell/hashmgr.cxx:9:
../deps/hunspell/src/hunspell/hashmgr.hxx:17:21: warning: private field 'userword' is not used [-Wunused-private-field]
  int               userword;
                    ^
1 warning generated.
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/hunspell.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/hunzip.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/phonet.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/replist.o
  CXX(target) Release/obj.target/hunspell/deps/hunspell/src/hunspell/suggestmgr.o
  LIBTOOL-STATIC Release/hunspell.a
  CXX(target) Release/obj.target/spellcheck/src/spellcheck.o
In file included from ../src/spellcheck.cc:5:
../node_modules/nan/nan.h:68:13: error: no type named 'UnboundScript' in namespace 'v8'
typedef v8::UnboundScript      NanUnboundScript;
        ~~~~^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
../node_modules/nan/nan_new.h:182:20: error: no member named 'UnboundScript' in namespace 'v8'
struct Factory<v8::UnboundScript> : FactoryBase<v8::UnboundScript> {
               ~~~~^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:29:25: error: cannot initialize a parameter of type 'int' with an rvalue of type
      'v8::Isolate *'
  return v8::Array::New(v8::Isolate::GetCurrent());
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:2335:31: note: passing argument to parameter 'length' here
  static Local<Array> New(int length = 0);
                              ^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:34:52: error: too many arguments to function call, expected at most single
      argument 'length', have 2 arguments
  return v8::Array::New(v8::Isolate::GetCurrent(), length);
         ~~~~~~~~~~~~~~                            ^~~~~~
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:2335:3: note: 'New' declared here
  static Local<Array> New(int length = 0);
  ^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:41:54: error: too many arguments to function call, expected single argument
      'value', have 2 arguments
  return v8::Boolean::New(v8::Isolate::GetCurrent(), value);
         ~~~~~~~~~~~~~~~~                            ^~~~~
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:5967:1: note: 'New' declared here
Handle<Boolean> Boolean::New(bool value) {
^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:64:51: error: too many arguments to function call, expected single argument
      'time', have 2 arguments
  return v8::Date::New(v8::Isolate::GetCurrent(), value).As<v8::Date>();
         ~~~~~~~~~~~~~                            ^~~~~
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:2866:3: note: 'New' declared here
  static Local<Value> New(double time);
  ^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:64:69: error: expected '(' for function-style cast or type construction
  return v8::Date::New(v8::Isolate::GetCurrent(), value).As<v8::Date>();
                                                            ~~~~~~~~^
../node_modules/nan/nan_implementation_12_inl.h:64:71: error: expected expression
  return v8::Date::New(v8::Isolate::GetCurrent(), value).As<v8::Date>();
                                                                      ^
../node_modules/nan/nan_implementation_12_inl.h:71:55: error: too many arguments to function call, expected single argument
      'value', have 2 arguments
  return v8::External::New(v8::Isolate::GetCurrent(), value);
         ~~~~~~~~~~~~~~~~~                            ^~~~~
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:3045:3: note: 'New' declared here
  static Local<External> New(void* value);
  ^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:90:37: error: cannot initialize a parameter of type 'FunctionCallback' (aka 'void
      (*)(const FunctionCallbackInfo<v8::Value> &)') with an rvalue of type 'v8::Isolate *'
  return v8::FunctionTemplate::New( v8::Isolate::GetCurrent()
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:3347:24: note: passing argument to parameter 'callback' here
      FunctionCallback callback = 0,
                       ^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:108:33: error: too many arguments to function call, expected single argument
      'value', have 2 arguments
                              , value).As<v8::NumberObject>();
                                ^~~~~
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:2904:3: note: 'New' declared here
  static Local<Value> New(double value);
  ^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:108:59: error: expected '(' for function-style cast or type construction
                              , value).As<v8::NumberObject>();
                                          ~~~~~~~~~~~~~~~~^
../node_modules/nan/nan_implementation_12_inl.h:108:61: error: expected expression
                              , value).As<v8::NumberObject>();
                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:128:7: error: no matching function for call to 'NewFromUnsigned'
      v8::Uint32::NewFromUnsigned(v8::Isolate::GetCurrent(), value));
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:1965:25: note: candidate function not viable: no known conversion from
      'v8::Isolate *' to 'uint32_t' (aka 'unsigned int') for 1st argument
  static Local<Integer> NewFromUnsigned(uint32_t value, Isolate*);
                        ^
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:1963:25: note: candidate function not viable: requires single argument
      'value', but 2 arguments were provided
  static Local<Integer> NewFromUnsigned(uint32_t value);
                        ^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:134:7: error: no matching function for call to 'NewFromUnsigned'
      v8::Uint32::NewFromUnsigned(v8::Isolate::GetCurrent(), value));
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:1965:25: note: candidate function not viable: no known conversion from
      'v8::Isolate *' to 'uint32_t' (aka 'unsigned int') for 1st argument
  static Local<Integer> NewFromUnsigned(uint32_t value, Isolate*);
                        ^
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:1963:25: note: candidate function not viable: requires single argument
      'value', but 2 arguments were provided
  static Local<Integer> NewFromUnsigned(uint32_t value);
                        ^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:141:26: error: too many arguments to function call, expected 0, have 1
  return v8::Object::New(v8::Isolate::GetCurrent());
         ~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:2307:3: note: 'New' declared here
  static Local<Object> New();
  ^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:148:10: error: no matching function for call to 'New'
  return v8::ObjectTemplate::New(v8::Isolate::GetCurrent());
         ^~~~~~~~~~~~~~~~~~~~~~~
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:3574:32: note: candidate function not viable: no known conversion from
      'v8::Isolate *' to 'Handle<v8::FunctionTemplate>' for 1st argument
  static Local<ObjectTemplate> New(Handle<FunctionTemplate> constructor);
                               ^
/Users/kamesharumugam/.node-gyp/0.11.9/deps/v8/include/v8.h:3433:32: note: candidate function not viable: requires 0 arguments,
      but 1 was provided
  static Local<ObjectTemplate> New();
                               ^
In file included from ../src/spellcheck.cc:5:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:164:7: error: no member named 'ScriptCompiler' in namespace 'v8'
  v8::ScriptCompiler::Source src(source);
  ~~~~^
../node_modules/nan/nan_implementation_12_inl.h:165:14: error: no member named 'ScriptCompiler' in namespace 'v8'
  return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &src);
         ~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/spellcheck/src/spellcheck.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:101:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:827:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Volumes/HD_II/spell/spellcheck
gyp ERR! node -v v0.11.9
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 


```

**Comment by mscdex** [comment]
Can you please try upgrading your version of node? You're on node v0.11.9 which is an (old) unstable version. Try with something like node v0.10, v0.12, or latest version of io.js.
